/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tts.task;

import tts.task.category.CategoryType;
import tts.task.entity.Customer;
import tts.task.entity.Movie;
import tts.task.entity.Rental;

public class App {
    public static void main(String[] args) {
        Movie movie1 = new Movie("Inception",CategoryType.NEW_RELEASE);
        Movie movie2 = new Movie("The Godfather", CategoryType.CLASSIC);
        Movie movie3 = new Movie("Spider-Man", CategoryType.REGULAR);

        Rental rental1 = new Rental(movie1, 2);
        Rental rental2 = new Rental(movie2, 3);
        Rental rental3 = new Rental(movie3, 4);

        Customer customer = new Customer("John Doe");
        customer.addRental(rental1);
        customer.addRental(rental2);
        customer.addRental(rental3);

        String statement = customer.generateStatement();

        System.out.println(statement);
    }
}
